## After APT is configured, this playbook will do the initial setup of linux.
---
- name: Basic Setup, add users & configure ssh.
  hosts: "*"
  become: true
  tasks:
    - name: Setup users/keys
      with_items:
        - frob
      ansible.builtin.user:
        name: "{{ item }}"
        create_home: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Add pubic key to user
      ansible.posix.authorized_key:
        user: frob
        state: present
        key: "{{ lookup('file', '/ansible/public_keys/id_rsa.pub') }}"

    - name: Setup sudo users
      ansible.builtin.user:
        name: frob
        groups: sudo
        append: true

    - name: Remove password based ssh
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication {{ sshd_PasswordAuthentication }}"
        validate: "sshd -t -f %s"
      notify: restart ssh service
      when: sshd_PasswordAuthentication is defined

    - name: "Enable auto updates: install unattended-upgrades apt-listchanges bsd-mailx"
      with_items:
        - unattended-upgrades
        - apt-listchanges
        - bsd-mailx
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes

    - name: Configure auto updates
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        search_string: '//        "origin=Debian,codename=${distro_codename},label=Debian";'
        line: '        "origin=Debian,codename=${distro_codename},label=Debian";'
        state: present

    - name: Configure auto updates
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        search_string: '//        "origin=Debian,codename=${distro_codename},label=Debian-Security";'
        line: '        "origin=Debian,codename=${distro_codename},label=Debian-Security";'
        state: present

    - name: Configure auto updates
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        search_string: '//        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";'
        line: '        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";'
        state: present

    - name: Enable and Start Unattended Upgrades
      ansible.builtin.systemd_service:
        name: unattended-upgrades
        state: started
        enabled: true

    - name: Time & Timezone setup
      community.general.timezone:
        name: America/Los_Angeles

    - name: "Install ufw"
      with_items:
        - ufw
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes

    - name: "Configure Firewall for SSH"
      community.general.ufw:
        rule: allow
        name: ssh
        state: enabled

    # handlers file for sshd-config
    - name: restart ssh service
      service:
        name: sshd
        state: restarted
